### ISSUE TITLE
 Uncaught ErrorException: Uncaught ErrorException: Swoole\Process::exec():

### ISSUE THREAD

**Issue by videni** [swoft-cloud/swoft-cli#20]
```
Fatal error: Uncaught ErrorException: Uncaught ErrorException: Swoole\Process::exec(): exec file name is empty in phar:///usr/local/bin/swoftcli/app/Command/ServeCommand.php:287
Stack trace:
#0 [internal function]: Swoft\Error\DefaultErrorDispatcher->handleError(2, 'Swoole\\Process:...', 'phar:///usr/loc...', 287, Array)
#1 phar:///usr/local/bin/swoftcli/app/Command/ServeCommand.php(287): Swoole\Process->exec('', Array)
#2 [internal function]: Swoft\Cli\Command\ServeCommand->Swoft\Cli\Command\{closure}(Object(Swoole\Process))
#3 phar:///usr/local/bin/swoftcli/app/Command/ServeCommand.php(290): Swoole\Process->start()
#4 phar:///usr/local/bin/swoftcli/app/Command/ServeCommand.php(235): Swoft\Cli\Command\ServeCommand->startServer()
#5 phar:///usr/local/bin/swoftcli/vendor/swoft/console/src/ConsoleDispatcher.php(46): Swoft\Cli\Command\ServeCommand->run(Object(Swoft\Console\Input\Input))
#6 phar:///usr/local/bin/swoftcli/vendor/swoft/console/src/Application.php(213): Swoft\Console\ConsoleDispatcher->dispatch(Array)
#7 phar:// in phar:///usr/local/bin/swoftcli/app/Command/ServeCommand.php on line 287
```

**Comment by inhere** [comment]
:) 提供一下，如何使用的

**Comment by videni** [comment]
closed, as  we need to specify the directory to serve, for example
```
 swoftcli serve:run .   // current directory
```

**Comment by liubangde88** [comment]
同样的问题，无法解决！！！！！！

**Comment by liubangde88** [comment]
swoftcli serve:run . 启动报这个错误，同样的问题，应该不是偶发性的
